name: "CI"
on:
  push:
    branches:
      - main

jobs:
  build-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          architecture: x64
          python-version: "3.10"
          cache: pipenv
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Make demo page
        run: |
          pipenv install
          pipenv run make revealjs
      - uses: actions/upload-artifact@v3
        with:
          name: sphinx-build
          path: build
  build-app:
    needs: build-content
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - uses: actions/download-artifact@v3
        with:
          name: sphinx-build
          path: build/
      - name: install app dependencies and build it
        run: yarn && yarn tauri build
